### ISSUE TITLE
MetalDock run fails after geometry optimisation

### ISSUE THREAD

**Issue by StefanIvanovIBBR** [MatthijsHak/MetalDock#22]
(MetalDock) stefan@stefan-Latitude-5521:~$ MetalDock/metaldock -i orca_input.ini 
GEOMETRY CONVERGED
[08:24:54] Explicit valence for atom # 1 N, 4, is greater than permitted
Traceback (most recent call last):
  File "MetalDock/metaldock", line 6, in <module>
    main()
  File "/home/stefan/MetalDock/src/metal_dock/main.py", line 18, in main
    docking(par)
  File "/home/stefan/MetalDock/src/metal_dock/docking.py", line 72, in docking
    qm_dir, energy = orca.orca_engine(xyz_file, par, output_dir)
  File "/home/stefan/MetalDock/src/metal_dock/orca_engine.py", line 24, in orca_engine
    orca_extract_CM5('geom.out', xyz_file)
  File "/home/stefan/MetalDock/src/metal_dock/orca_engine.py", line 72, in orca_extract_CM5
    qcm5 = oc.HirshfeldToCM5(xyz_file, data, a0)
  File "/home/stefan/MetalDock/src/metal_dock/orca2CM5.py", line 95, in HirshfeldToCM5
    df['FPS'] = [AtomFPProgram(mol,atomNum,radii=2) for atomNum in df.index]
  File "/home/stefan/MetalDock/src/metal_dock/orca2CM5.py", line 95, in <listcomp>
    df['FPS'] = [AtomFPProgram(mol,atomNum,radii=2) for atomNum in df.index]
  File "/home/stefan/MetalDock/src/metal_dock/orca2CM5.py", line 19, in AtomFPProgram
    env = Chem.FindAtomEnvironmentOfRadiusN(hmol,radii,atomNum,useHs=True)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.FindAtomEnvironmentOfRadiusN(NoneType, int, int)
did not match C++ signature:
    FindAtomEnvironmentOfRadiusN(RDKit::ROMol mol, unsigned int radius, unsigned int rootedAtAtom, bool useHs=False, bool enforceSize=True, boost::python::api::object atomMap=None)
[orca_input.zip](https://github.com/MatthijsHak/MetalDock/files/15033492/orca_input.zip)

**Comment by StefanIvanovIBBR** [comment]
Please see the attached input files.

**Comment by MatthijsHak** [comment]
Hi,

I have fixed the problem and I can now run your calculations smoothly. Could you rerun the calculations with the new repo and let me know if you run into any problems?

Thanks.

**Comment by StefanIvanovIBBR** [comment]
Thanks.

I'll rerun and let you know how it went.

Best wishes,

Stefan

**Comment by StefanIvanovIBBR** [comment]
Problem solved, many thanks @MatthijsHak !
