### ISSUE TITLE
UnboundLocalError: local variable 'branch_id' referenced before assignment

### ISSUE THREAD

**Issue by rjrich** [MatthijsHak/MetalDock#33]
GEOMETRY CONVERGED
SPACING BETWEEN GRID POINTS IS STANDARD SET TO 0.375 Å
BOX SIZE MUST BE INTEGER GRID POINTS WHICH WAS NOT FOUND
BOX SIZE SIDE ROUNDED UP AND SET TO 24.060 Å

Traceback (most recent call last):
  File "/home/rjrich/MetalDock/metaldock", line 6, in <module>
    main()
  File "/home/rjrich/MetalDock/src/metal_dock/main.py", line 18, in main
    docking(par)
  File "/home/rjrich/MetalDock/src/metal_dock/docking.py", line 147, in docking
    d.create_ligand_pdbqt_file(par, par.name_ligand)
  File "/home/rjrich/MetalDock/src/metal_dock/prepare_dock.py", line 475, in create_ligand_pdbqt_file
    multiple_model_file(par, name_ligand, f'{name_ligand}_c.xyz', f'{name_ligand}.pdbqt')
  File "/home/rjrich/MetalDock/src/metal_dock/prepare_dock.py", line 575, in multiple_model_file
    new_pdbqt.append(['BRANCH',f'{metal_atom}',f'{branch_id}'])
=====

**Comment by MatthijsHak** [comment]
I believe I have fixed your problem. Could you use the latest repository and verify if it works for your system?
