### ISSUE TITLE
ModuleNotFoundError: No module named 'xtb calling metaldock on Ubuntu 22.04

### ISSUE THREAD

**Issue by xavgit** [MatthijsHak/MetalDock#41]
Hi,
when I call ./metaldock I receive the following:
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~/sources/MetalDock$ ./metaldock 
Traceback (most recent call last):
  File "./metaldock", line 3, in <module>
    from src.metal_dock.main import main
  File "/home/xxxx/sources/MetalDock/src/metal_dock/main.py", line 6, in <module>
    from .docking import docking
  File "/home/xxxx/sources/MetalDock/src/metal_dock/docking.py", line 9, in <module>
    from xtb.ase.calculator import XTB
ModuleNotFoundError: No module named 'xtb'

Before calling metaldock I run the following  to check if xtb is installed:
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~/sources/MetalDock$ conda install numpy ase xtb 
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

\# All requested packages already installed.

Thanks.

Saverio

**Comment by MatthijsHak** [comment]
Hi, 

Can you verify the installation of xtb by starting python and importing xtb. Otherwise can you type which python and verify that you are using the python of the correct environment.

**Comment by xavgit** [comment]
Hi,
yes, the output .... ( if I have understood what you need):
xxxx@xxxx-X399-DESIGNARE-EX:~$ conda activate MetalDock 
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~$ python
Python 3.8.20 (default, Oct  3 2024, 15:24:27) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xtb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xtb'
>>> 
[1]+  Stopped                 python
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~$ which python
/home/xxxx/miniconda3/envs/MetalDock/bin/python

Thanks. 

Saverio

**Comment by MatthijsHak** [comment]
Okay it looks like that xtb is not installed correctly in your conda environment. If it states that it is present, please remove / uninstall xtb and reinstall it to see if that will work.

**Comment by xavgit** [comment]
Hi,
here ....
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~$ conda remove xtb
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/xxxx/miniconda3/envs/MetalDock

  removed specs:
    - xtb


The following packages will be REMOVED:

  dftd4-3.6.0-hf49bc11_0
  libblas-3.9.0-1_h86c2bf4_netlib
  liblapack-3.9.0-6_ha36c22a_netlib
  mctc-lib-0.3.1-h74f4db8_0
  simple-dftd3-1.0.0-hd59d2e7_0
  tblite-0.3.0-hf49bc11_1
  toml-f-0.4.2-hd8f1df9_0
  xtb-6.6.1-hf49bc11_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~$ conda install xtb 
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
Retrieving notices: ...working... done
/home/xxxx/miniconda3/lib/python3.11/site-packages/conda/base/context.py:982: FutureWarning: Adding 'defaults' to the channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly via 'conda config --add channels <name>', e.g. 'conda config --add channels defaults'.
  deprecated.topic(
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/xxxx/miniconda3/envs/MetalDock

  added / updated specs:
    - xtb


The following NEW packages will be INSTALLED:

  dftd4              conda-forge/linux-64::dftd4-3.6.0-hf49bc11_0 
  libblas            conda-forge/linux-64::libblas-3.9.0-1_h86c2bf4_netlib 
  liblapack          conda-forge/linux-64::liblapack-3.9.0-6_ha36c22a_netlib 
  mctc-lib           conda-forge/linux-64::mctc-lib-0.3.1-h74f4db8_0 
  simple-dftd3       conda-forge/linux-64::simple-dftd3-1.0.0-hd59d2e7_0 
  tblite             conda-forge/linux-64::tblite-0.3.0-hf49bc11_1 
  toml-f             conda-forge/linux-64::toml-f-0.4.2-hd8f1df9_0 
  xtb                conda-forge/linux-64::xtb-6.6.1-hf49bc11_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(MetalDock) xxxx@xxxx-X399-DESIGNARE-EX:~$ /home/xxxx/sources/MetalDock/metaldock 
Traceback (most recent call last):
  File "/home/xxxx/sources/MetalDock/metaldock", line 3, in <module>
    from src.metal_dock.main import main
  File "/home/xxxx/sources/MetalDock/src/metal_dock/main.py", line 6, in <module>
    from .docking import docking
  File "/home/xxxx/sources/MetalDock/src/metal_dock/docking.py", line 9, in <module>
    from xtb.ase.calculator import XTB
ModuleNotFoundError: No module named 'xtb'

**Comment by MatthijsHak** [comment]
Hi,

Weird from conda. In my experience micromamba works better. It is at least faster. You can try with that. Otherwise I would recommend to primarily using pip to install all the other packages. I do not see a reason why conda would be definitely needed.
